# Generated by Django 5.1.4 on 2024-12-09 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uscitech_academy', '0003_remove_student_grade_student_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('impregnation', 'Imprégnation'), ('pedagogique', 'Pédagogique'), ('entreprise', 'Entreprise')])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uscitech_academy.student')),
            ],
        )
    ]
