# Generated by Django 5.1.4 on 2024-12-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0004_stage_created_at_stage_end_date_stage_horraires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='facture',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
