# Generated by Django 5.1.4 on 2024-12-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0005_stage_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='horraire_status',
            field=models.BooleanField(default=False),
        ),
    ]
