# Generated by Django 5.1.4 on 2024-12-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0006_stage_horraire_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='institution_provisor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='institution_provisor_provisor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
