# Generated by Django 5.1.4 on 2025-01-07 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0007_stage_institution_provisor_and_more'),
        ('uscitech_academy', '0005_remove_student_first_name_remove_student_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagemaster',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uscitech_academy.gradeclasse'),
        ),
    ]
