# Generated by Django 5.1.5 on 2025-01-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0008_stagemaster_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='quote',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
