# Generated by Django 5.1.5 on 2025-01-22 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0009_stage_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='quote_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_by', to='isp_stage.stagemaster'),
        ),
        migrations.RemoveField(
            model_name='stage',
            name='stagemaster',
        ),
        migrations.AddField(
            model_name='stage',
            name='stagemaster',
            field=models.ManyToManyField(to='isp_stage.stagemaster'),
        ),
    ]
