# Generated by Django 5.1.5 on 2025-01-23 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0010_stage_quote_by_remove_stage_stagemaster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagemaster',
            name='dept',
        ),
    ]
