# Generated by Django 5.1.5 on 2025-01-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0011_remove_stagemaster_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='quote_status',
            field=models.CharField(choices=[('submitted', 'Soumie'), ('draft', 'Brouillon')], default='draft'),
        ),
    ]
