# Generated by Django 5.1.5 on 2025-01-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0012_stage_quote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagemaster',
            name='is_quote_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
