# Generated by Django 5.1.5 on 2025-02-12 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0013_stagemaster_is_quote_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetTutore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.TextField()),
            ],
        ),
    ]
