# Generated by Django 5.1.5 on 2025-02-16 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0014_projettutore'),
        ('uscitech_academy', '0005_remove_student_first_name_remove_student_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projettutore',
            name='head',
            field=models.ForeignKey(default='39f54546-3783-465d-8d06-a5cb22598804', on_delete=django.db.models.deletion.CASCADE, related_name='head', to='uscitech_academy.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projettutore',
            name='member',
            field=models.ManyToManyField(related_name='member', to='uscitech_academy.student'),
        ),
    ]
