# Generated by Django 5.1.5 on 2025-02-16 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0015_projettutore_head_projettutore_member'),
        ('uscitech_academy', '0006_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='projettutore',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uscitech_academy.teacher'),
        ),
    ]
