# Generated by Django 5.1.5 on 2025-02-16 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0016_projettutore_teacher'),
        ('uscitech_academy', '0006_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMemoire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='uscitech_academy.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uscitech_academy.teacher')),
            ],
        ),
    ]
