# Generated by Django 5.1.5 on 2025-02-16 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0017_studentmemoire'),
        ('uscitech_academy', '0006_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_teacher_tutore_project_group', models.IntegerField(default=0)),
                ('max_teacher_memoire', models.IntegerField(default=0)),
                ('max_tutore_project_member_group', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uscitech_academy.gradeclasse')),
            ],
        ),
    ]
