# Generated by Django 5.1.5 on 2025-02-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0018_departmentsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentsettings',
            name='max_teacher_memoire',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='departmentsettings',
            name='max_teacher_tutore_project_group',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='departmentsettings',
            name='max_tutore_project_member_group',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
