# Generated by Django 5.1.5 on 2025-02-20 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_department_head_department_responsible'),
        ('isp_stage', '0019_alter_departmentsettings_max_teacher_memoire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deptrechercheofficier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stagemaster',
            name='user',
        ),
        migrations.AddField(
            model_name='deptrechercheofficier',
            name='employee',
            field=models.OneToOneField(default='dedf88c3-d884-43bb-8e01-f2d928394ab1', on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagemaster',
            name='employee',
            field=models.OneToOneField(default='dedf88c3-d884-43bb-8e01-f2d928394ab1', on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
            preserve_default=False,
        ),
    ]
