# Generated by Django 5.1.5 on 2025-02-25 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_department_head_department_responsible'),
        ('isp_stage', '0019_alter_departmentsettings_max_teacher_memoire_and_more'),
        ('uscitech_academy', '0006_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deptrechercheofficier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projettutore',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='stagemaster',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentmemoire',
            name='teacher',
        ),
        migrations.AddField(
            model_name='departmentsettings',
            name='max_teacher_externe_memoire',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='departmentsettings',
            name='max_teacher_externe_tutore_project_group',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='deptrechercheofficier',
            name='employee',
            field=models.OneToOneField(default='e9c17ba3-beab-4138-a889-ee4e15064178', on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagemaster',
            name='employee',
            field=models.OneToOneField(default='e9c17ba3-beab-4138-a889-ee4e15064178', on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DirecteurTravaux',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction_type', models.CharField(choices=[('projet-tutore', 'Projet Tutoré'), ('memoire', 'Mémoire'), ('stage', 'Stage')])),
                ('category', models.CharField(choices=[('interne', 'Du Département'), ('externe', 'Pas du Département')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uscitech_academy.gradeclasse')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.AddField(
            model_name='projettutore',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isp_stage.directeurtravaux'),
        ),
        migrations.AddField(
            model_name='studentmemoire',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isp_stage.directeurtravaux'),
        ),
    ]
