# Generated by Django 5.1.5 on 2025-02-19 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_department_head_department_responsible'),
        ('isp_stage', '0020_remove_deptrechercheofficier_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagemaster',
            name='user',
        ),
        migrations.AddField(
            model_name='stagemaster',
            name='employee',
            field=models.OneToOneField(default='39b4f280-9ab5-43c5-8444-817b71ffbe20', on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
            preserve_default=False,
        ),
    ]
