# Generated by Django 5.1.5 on 2025-02-20 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_department_head_department_responsible'),
        ('isp_stage', '0021_remove_stagemaster_user_stagemaster_employee'),
        ('uscitech_academy', '0006_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirecteurTravaux',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction_type', models.CharField(choices=[('projet-tutore', 'Projet Tutoré'), ('memoire', 'Mémoire'), ('stage', 'Stage')])),
                ('category', models.CharField(choices=[('interne', 'Du Département'), ('externe', 'Pas du Département')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uscitech_academy.gradeclasse')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
