# Generated by Django 5.1.5 on 2025-02-20 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0022_directeurtravaux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projettutore',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='studentmemoire',
            name='teacher',
        ),
        migrations.AddField(
            model_name='projettutore',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isp_stage.directeurtravaux'),
        ),
        migrations.AddField(
            model_name='studentmemoire',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isp_stage.directeurtravaux'),
        ),
    ]
