# Generated by Django 5.1.5 on 2025-02-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0023_remove_projettutore_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentsettings',
            name='max_teacher_externe_tutore_project_group',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
