# Generated by Django 5.1.5 on 2025-02-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_stage', '0024_departmentsettings_max_teacher_externe_tutore_project_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentsettings',
            name='max_teacher_externe_memoire',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
